### PR TITLE
ESP8622 port

### PR DESCRIPTION
**Pull request by jeremypoulter**
Fixes to build on ESP8266, runs out of memory very quickly but a few fixes and some general tidy up

### CODE REVIEW

**Comment by glynhudson** [comment]
Should this PR be tested and merged? Or is it just a placeholder?

**Comment by jeremypoulter** [comment]
Kind of handy to merge, just to get the compiling working, and there are a few bits of tidy up

**Comment by glynhudson** [comment]
Compile error:

`src/web_server.cpp:872:28: error: 'class HalEsp32' has no member named 'getUpdateSize'`

**Comment by glynhudson** [comment]
This merger has been reverted, I'm not sure how to re-open this PR

**Pull request merged**
