### PR TITLE
OpenEVSE WiFi v1 support

### PR DESCRIPTION
**Pull request by jeremypoulter**
Initial support for the OpenEVSE WiFi v1 board, #91 and #92

### CODE REVIEW

**Comment by jeremypoulter** [comment]
@chris1howell I have added the LED support and the temp sensor support although the latter does not look to be finding the sensor. Are you able to test?

**Comment by chris1howell** [comment]
@jeremypoulter <https://github.com/jeremypoulter> Temperature sensor is
working by adding the following:

input .h
#ifdef ENABLE_MCP9808
Wire.begin(I2C_SDA, I2C_SCL);

platform.ini
-DI2C_SDA=21
-DI2C_SCL=22

LEDs do not seem to be working, I do see the LED Manager messages in Debug
but color stays white.

Additionally, I can not save MQTT in the UI. I keep getting "Failed to save
Config" messages.

**Comment by jeremypoulter** [comment]
Added a fix for those issues, looks like using Serial2 breaks the NeoPixel, Could not get Serial1 to work so left the debug on Serial for now :( 

I2C now initialised on the correct pins, sorry I missed that in the sample code. Getting a value now, but looks to be 10 degrees higher than it should be...

**Comment by chris1howell** [comment]
Great work.... Both LED and temp are working. I am also seeing the same
+10C on the temp sensor, will look into it.

LEDs look great, using one LED for WiFi status and the other for EVSE
status is really cool. Works perfectly when the station is connected to
WiFi as a client. I did note the station does not change color for EVSE
status when in AP mode (with no device connected) and in AP mode connected
as standalone. The LED stays green for "Ready", "Connected" and "Charging",
Red error states seem to work in all states.

**Comment by jeremypoulter** [comment]
> LEDs look great, using one LED for WiFi status and the other for EVSE status is really cool

Not exactly what was intended, can you send a video... I did notice on my board there is a slight colour difference between the two LEDs... 

> Works perfectly when the station is connected to WiFi as a client. I did note the station does not change color for EVSE status when in AP mode (with no device connected) and in AP mode connected as standalone.

That was the intention, the LED should be used for WiFi or error states when connecting and the EVSE state when connected to the WiFi.

**Comment by chris1howell** [comment]
The EVSE state must always be displayed visualy, it is a requirement of UL,
J1772 and IEC. WiFi State is not required by any regulation. When on the
road using a portable station (no LCD display) in "Standalone Mode" EVSE
status is still needed, there are many use cases where WiFi is not used or
avaliable.

My suggestion would be to use one LED for station status and the second for
WiFi visual feedback.

**Pull request merged**
